[package]
name = "ruda_client"
description = "Client-side game state"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
glam.workspace = true
ruda_core.workspace = true
ruda_net.workspace = true
ruda_protocol.workspace = true
ruda_world.workspace = true

[dev-dependencies]
ruda_base.workspace = true
ruda_server.workspace = true

[lints]
workspace = true
