[package]
name = "ruda_render"
description = "wgpu renderer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
tracing.workspace = true
wgpu.workspace = true

[lints]
workspace = true
