[package]
name = "ruda_render"
description = "wgpu renderer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
glam.workspace = true
png.workspace = true
rayon.workspace = true
ruda_core.workspace = true
ruda_world.workspace = true
tracing.workspace = true
wgpu.workspace = true

[dev-dependencies]
naga = { version = "30.0.0", features = ["wgsl-in"] }

[lints]
workspace = true
