[package]
name = "ruda_net"
description = "Connections between the client and the server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
ruda_protocol.workspace = true
serde.workspace = true
thiserror.workspace = true

[lints]
workspace = true
